package com.kazforge.jsonapi.core.validation;

/**
 * Stable rule codes for JSON:API validation failures.
 *
 * <p>Public diagnostic contract for {@link JsonApiValidationException}: callers may match on these
 * codes rather than exception messages. Codes cover both local construction failures and aggregate
 * validator failures. See {@code docs/conformance.md} for which rules are enforced.
 */
public enum ValidationRuleCode {
  INVALID_MEMBER_NAME,
  INVALID_URI_REFERENCE,
  INVALID_LINK_RELATION,
  INVALID_LANGUAGE_TAG,
  INVALID_MEDIA_TYPE,
  INVALID_EXTENSION_URI,
  INVALID_PROFILE_URI,
  INVALID_OPEN_JSON_VALUE,
  INVALID_JSON_POINTER,
  MEMBER_NAME_COLLISION,
  RESERVED_FIELD_NAME,
  MISSING_RESOURCE_TYPE,
  MISSING_RESOURCE_ID,
  MISSING_ERROR_MEMBER,
  MISSING_RELATIONSHIP_MEMBER,
  MISSING_TOP_LEVEL_MEMBER,
  DATA_ERRORS_COEXIST,
  INCLUDED_WITHOUT_DATA,
  UNKNOWN_ADDITIONAL_MEMBER,
  DISALLOWED_ADDITIONAL_MEMBER,
  DUPLICATE_RESOURCE_IDENTITY,
  ENDPOINT_IDENTITY_MISMATCH,
  FULL_LINKAGE_VIOLATION,
  INCONSISTENT_LOCAL_IDENTIFIER,
  INCLUDED_RESOURCE_IDENTITY_REQUIRED,
  RESOURCE_ID_REQUIRED,
  NULL_RELATIONSHIP_VALUE,
  INVALID_LINKS_CONTEXT,
  RELATIONSHIP_DATA_REQUIRED,
  PAGINATION_REQUIRES_COLLECTION,
  NULL_COLLECTION_PAYLOAD,
  NULL_COLLECTION_ELEMENT,
  NULL_REQUIRED_VALUE,
  UPDATE_REQUIRES_SINGLE_RESOURCE,
  CREATE_REQUIRES_SINGLE_RESOURCE
}
